GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSYWZsaSIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNjc1NjU4NzAyLCJleHAiOjE2NzU2NTg3MjJ9.5n-qrzV6HxKnznZeb18y8RuK1WfGQBKZeXgV3EnRGM4

###
POST  http://localhost:5000/users
Content-Type: application/json

{
  "name": "Rafli 2",
  "email": "email2@gmail.com",
  "password": "1234",
  "confPassword": "12345"
}

###
POST  http://localhost:5000/login
Content-Type: application/json

{
  "email": "email@gmail.com",
  "password": "12345"
}