### GET DATA
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJSYWZsaSIsImVtYWlsIjoiZW1haWxAZ21haWwuY29tIiwiaWF0IjoxNjc1NzQ3NjU4LCJleHAiOjE2NzU3NDc2Nzh9.DxxWvoj3pLkSE5GlR12oiI27peDukIFw8x6b_Ttb4m0

### REGISTER
POST  http://localhost:5000/users
Content-Type: application/json

{
  "name": "Rafli 2",
  "email": "email2@gmail.com",
  "password": "1234",
  "confPassword": "12345"
}

### LOGIN
POST  http://localhost:5000/login
Content-Type: application/json

{
  "email": "email@gmail.com",
  "password": "12345"
}

### GET TOKEN
GET  http://localhost:5000/token

### LOGOUT
DELETE http://localhost:5000/logout